apiVersion: v1
kind: Pod
metadata:
  name: consumer-envar
spec:
  containers:
  - name: consumer-envar
    image: jboss/wildfly
    env:
    - name: DATA_NAME
      valueFrom:
        configMapKeyRef:
          name: configmap-example
          key: data.name
    - name: DATA_TYPE
      valueFrom:
        configMapKeyRef:
          name: configmap-example
          key: data.type
    - name: DATA_ROLE
      valueFrom:
        configMapKeyRef:
          name: configmap-example
          key: data.role
