apiVersion: v1
kind: Pod
metadata:
  name: consumer-volume
spec:
  containers:
  - name: consumer-volume
    image: jboss/wildfly
    volumeMounts:
      - name: config-volume
        mountPath: /data/config
  volumes:
    - name: config-volume
      configMap:
        name: configmap-example
        items:
          - key: data.file
            path: file/configuration.cnf
