apiVersion: v1
kind: Service
metadata:
  name: wildfly-ing-svc
  labels:
    run: wildfly-ing-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: wildfly
    exps: ingress
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wildfly-ing
spec:
  backend:
    serviceName: wildfly-ing-svc
    servicePort: 80
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: wildfly-ing-app
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: wildfly
        exps: ingress
        tier: frontend
        role: app-server
    spec:
      containers:
      - name: wildfly
        image: jboss/wildfly
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
          initialDelaySeconds: 15
          timeoutSeconds: 1
